version: '3'

services:
  fastapi:
    build:
      context: .
      target: development
    container_name: music-fastapi
    ports:
      - ${PORT:-8000}:${PORT:-8000}
    environment:
      PORT: ${PORT:-8000}
      DATABASE_URL: "postgresql://postgres:postgres@db:5432"
      DEBUG: 1
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./app:/code/app

  db:
    image: postgres:14-alpine
    container_name: music-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
