"""songs_block

Revision ID: 7946a8187afe
Revises: 7e820043c0d2
Create Date: 2022-04-25 13:30:15.528369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7946a8187afe'
down_revision = '7e820043c0d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('blocked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('songs', 'blocked')
    # ### end Alembic commands ###
