"""Albums block

Revision ID: 81838ad6f94a
Revises: 7946a8187afe
Create Date: 2022-04-25 13:38:31.594474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81838ad6f94a'
down_revision = '7946a8187afe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('albums', sa.Column('blocked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('albums', 'blocked')
    # ### end Alembic commands ###
