"""Description. Collaborative playlists

Revision ID: 998741a18065
Revises: 754d18060c81
Create Date: 2022-05-10 02:51:00.383936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '998741a18065'
down_revision = '754d18060c81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('albums', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('playlists', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('playlists', sa.Column('collaborative', sa.Boolean(), nullable=True))
    op.drop_column('playlists', 'colaborativa')
    op.add_column('songs', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('songs', sa.Column('file_uri', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('songs', 'file_uri')
    op.drop_column('songs', 'description')
    op.add_column('playlists', sa.Column('colaborativa', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('playlists', 'collaborative')
    op.drop_column('playlists', 'description')
    op.drop_column('albums', 'description')
    # ### end Alembic commands ###
